export const Metazoa = {
  // =================================================================
  // FAMOUS EXAMPLES (Theropods & Sharks)
  // =================================================================
  TyrannosaurusRex: { name: "Tyrannosaurus Rex", cladeList: ["Tyrannosaurus rex", "Tyrannosauridae", "Tyrannosauroidea", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Archosauromorpha", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Megalodon: { name: "Megalodon", cladeList: ["Otodus megalodon", "Lamniformes", "Galeomorphii", "Selachimorpha", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 1: THEROPOD DINOSAURS
  // =================================================================
  Velociraptor: { name: "Velociraptor", cladeList: ["Velociraptor mongoliensis", "Dromaeosauridae", "Eumaniraptora", "Paraves", "Maniraptora", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Spinosaurus: { name: "Spinosaurus", cladeList: ["Spinosaurus aegyptiacus", "Spinosauridae", "Megalosauroidea", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Allosaurus: { name: "Allosaurus", cladeList: ["Allosaurus fragilis", "Allosauridae", "Allosauroidea", "Carnosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Giganotosaurus: { name: "Giganotosaurus", cladeList: ["Giganotosaurus carolinii", "Carcharodontosauridae", "Allosauroidea", "Carnosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Dilophosaurus: { name: "Dilophosaurus", cladeList: ["Dilophosaurus wetherilli", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Carnotaurus: { name: "Carnotaurus", cladeList: ["Carnotaurus sastrei", "Ceratosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Ceratosaurus: { name: "Ceratosaurus", cladeList: ["Ceratosaurus nasicornis", "Ceratosauria", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Deinonychus: { name: "Deinonychus", cladeList: ["Deinonychus antirrhopus", "Dromaeosauridae", "Eumaniraptora", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Compsognathus: { name: "Compsognathus", cladeList: ["Compsognathus longipes", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Gallimimus: { name: "Gallimimus", cladeList: ["Gallimimus bullatus", "Maniraptoriformes", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Therizinosaurus: { name: "Therizinosaurus", cladeList: ["Therizinosaurus cheloniformis", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Baryonyx: { name: "Baryonyx", cladeList: ["Baryonyx walkeri", "Spinosauridae", "Megalosauroidea", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Albertosaurus: { name: "Albertosaurus", cladeList: ["Albertosaurus sarcophagus", "Tyrannosauridae", "Tyrannosauroidea", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Oviraptor: { name: "Oviraptor", cladeList: ["Oviraptor philoceratops", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Troodon: { name: "Troodon", cladeList: ["Troodon formosus", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Cryolophosaurus: { name: "Cryolophosaurus", cladeList: ["Cryolophosaurus ellioti", "Tetanurae", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 2: SAUROPODS
  // =================================================================
  Brachiosaurus: { name: "Brachiosaurus", cladeList: ["Brachiosaurus altithorax", "Brachiosauridae", "Macronaria", "Camarasauromorpha", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Diplodocus: { name: "Diplodocus", cladeList: ["Diplodocus carnegii", "Diplodocidae", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Apatosaurus: { name: "Apatosaurus", cladeList: ["Apatosaurus ajax", "Diplodocidae", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Argentinosaurus: { name: "Argentinosaurus", cladeList: ["Argentinosaurus huinculensis", "Colossosauria", "Titanosauria", "Macronaria", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Amargasaurus: { name: "Amargasaurus", cladeList: ["Amargasaurus cazaui", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Camarasaurus: { name: "Camarasaurus", cladeList: ["Camarasaurus supremus", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Giraffatitan: { name: "Giraffatitan", cladeList: ["Giraffatitan brancai", "Brachiosauridae", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Dreadnoughtus: { name: "Dreadnoughtus", cladeList: ["Dreadnoughtus schrani", "Titanosauria", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Patagotitan: { name: "Patagotitan", cladeList: ["Patagotitan mayorum", "Colossosauria", "Titanosauria", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Mamenchisaurus: { name: "Mamenchisaurus", cladeList: ["Mamenchisaurus constructus", "Eusauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 3: ORNITHISCHIAN DINOSAURS
  // =================================================================
  Triceratops: { name: "Triceratops", cladeList: ["Triceratops horridus", "Ceratopsidae", "Ceratopsia", "Marginocephalia", "Cerapoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Stegosaurus: { name: "Stegosaurus", cladeList: ["Stegosaurus stenops", "Stegosauridae", "Stegosauria", "Eurypoda", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Ankylosaurus: { name: "Ankylosaurus", cladeList: ["Ankylosaurus magniventris", "Ankylosauridae", "Ankylosauria", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Parasaurolophus: { name: "Parasaurolophus", cladeList: ["Parasaurolophus walkeri", "Hadrosauridae", "Hadrosauroidea", "Iguanodontia", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Iguanodon: { name: "Iguanodon", cladeList: ["Iguanodon bernissartensis", "Iguanodontia", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Pachycephalosaurus: { name: "Pachycephalosaurus", cladeList: ["Pachycephalosaurus wyomingensis", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Styracosaurus: { name: "Styracosaurus", cladeList: ["Styracosaurus albertensis", "Ceratopsidae", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Protoceratops: { name: "Protoceratops", cladeList: ["Protoceratops andrewsi", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Edmontosaurus: { name: "Edmontosaurus", cladeList: ["Edmontosaurus annectens", "Saurolophinae", "Hadrosauridae", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Kentrosaurus: { name: "Kentrosaurus", cladeList: ["Kentrosaurus aethiopicus", "Stegosauridae", "Stegosauria", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Maiasaura: { name: "Maiasaura", cladeList: ["Maiasaura peeblesorum", "Saurolophinae", "Hadrosauridae", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Euoplocephalus: { name: "Euoplocephalus", cladeList: ["Euoplocephalus tutus", "Ankylosauridae", "Ankylosauria", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Psittacosaurus: { name: "Psittacosaurus", cladeList: ["Psittacosaurus mongoliensis", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hypsilophodon: { name: "Hypsilophodon", cladeList: ["Hypsilophodon foxii", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 4: PTEROSAURS
  // =================================================================
  Pteranodon: { name: "Pteranodon", cladeList: ["Pteranodon longiceps", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Quetzalcoatlus: { name: "Quetzalcoatlus", cladeList: ["Quetzalcoatlus northropi", "Azhdarchidae", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Dimorphodon: { name: "Dimorphodon", cladeList: ["Dimorphodon macronyx", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Rhamphorhynchus: { name: "Rhamphorhynchus", cladeList: ["Rhamphorhynchus muensteri", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Tapejara: { name: "Tapejara", cladeList: ["Tapejara wellnhoferi", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hatzegopteryx: { name: "Hatzegopteryx", cladeList: ["Hatzegopteryx thambema", "Azhdarchidae", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 5: MARINE REPTILES
  // =================================================================
  Mosasaurus: { name: "Mosasaurus", cladeList: ["Mosasaurus hoffmannii", "Mosasauridae", "Mosasauroidea", "Squamata", "Lepidosauria", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Plesiosaurus: { name: "Plesiosaurus", cladeList: ["Plesiosaurus dolichodeirus", "Plesiosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Ichthyosaurus: { name: "Ichthyosaurus", cladeList: ["Ichthyosaurus communis", "Ichthyosauria", "Ichthyosauromorpha", "Diapsida", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Elasmosaurus: { name: "Elasmosaurus", cladeList: ["Elasmosaurus platyurus", "Plesiosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Liopleurodon: { name: "Liopleurodon", cladeList: ["Liopleurodon ferox", "Pliosauridae", "Pliosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Kronosaurus: { name: "Kronosaurus", cladeList: ["Kronosaurus queenslandicus", "Pliosauridae", "Pliosauroidea", "Plesiosauria", "Sauropterygia", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Tylosaurus: { name: "Tylosaurus", cladeList: ["Tylosaurus proriger", "Mosasauridae", "Mosasauroidea", "Squamata", "Lepidosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Shonisaurus: { name: "Shonisaurus", cladeList: ["Shonisaurus popularis", "Ichthyosauria", "Ichthyosauromorpha", "Diapsida", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 6: EXTINCT MAMMALS
  // =================================================================
  WoollyMammoth: { name: "Woolly Mammoth", cladeList: ["Mammuthus primigenius", "Proboscidea", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Mammaliaformes", "Cynodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Smilodon: { name: "Smilodon", cladeList: ["Smilodon fatalis", "Feliformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  WoollyRhino: { name: "Woolly Rhino", cladeList: ["Coelodonta antiquitatis", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Megatherium: { name: "Megatherium", cladeList: ["Megatherium americanum", "Folivora", "Pilosa", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Paraceratherium: { name: "Paraceratherium", cladeList: ["Paraceratherium transouralicum", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  DireWolf: { name: "Dire Wolf", cladeList: ["Aenocyon dirus", "Caniformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Glyptodon: { name: "Glyptodon", cladeList: ["Glyptodon clavipes", "Chlamyphoridae", "Cingulata", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Andrewsarchus: { name: "Andrewsarchus", cladeList: ["Andrewsarchus mongoliensis", "Cetancodontamorpha", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Daeodon: { name: "Daeodon", cladeList: ["Daeodon shoshonensis", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hyaenodon: { name: "Hyaenodon", cladeList: ["Hyaenodon horridus", "Hyaenodonta", "Ferae", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  CaveBear: { name: "Cave Bear", cladeList: ["Ursus spelaeus", "Caniformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  IrishElk: { name: "Irish Elk", cladeList: ["Megaloceros giganteus", "Ruminantia", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Diprotodon: { name: "Diprotodon", cladeList: ["Diprotodon optatum", "Vombatiformes", "Diprotodontia", "Australidelphia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Thylacoleo: { name: "Thylacoleo", cladeList: ["Thylacoleo carnifex", "Vombatiformes", "Diprotodontia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Procoptodon: { name: "Procoptodon", cladeList: ["Procoptodon goliah", "Macropodiformes", "Diprotodontia", "Marsupialia", "Metatheria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Mastodon: { name: "Mastodon", cladeList: ["Mammut americanum", "Proboscidea", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Basilosaurus: { name: "Basilosaurus", cladeList: ["Basilosaurus cetoides", "Pelagiceti", "Cetacea", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  GiantBeaver: { name: "Giant Beaver", cladeList: ["Castoroides ohioensis", "Castorimorpha", "Rodentia", "Euarchontoglires", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Macrauchenia: { name: "Macrauchenia", cladeList: ["Macrauchenia patachonica", "Litopterna", "Meridiungulata", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Doedicurus: { name: "Doedicurus", cladeList: ["Doedicurus clavicaudatus", "Chlamyphoridae", "Cingulata", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 7: RECENTLY EXTINCT
  // =================================================================
  Dodo: { name: "Dodo", cladeList: ["Raphus cucullatus", "Columbidae", "Columbiformes", "Columbimorphae", "Neoaves", "Neognathae", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  TasmanianTiger: { name: "Tasmanian Tiger", cladeList: ["Thylacinus cynocephalus", "Dasyuromorphia", "Australidelphia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Moa: { name: "Moa", cladeList: ["Dinornis robustus", "Dinornithiformes", "Palaeognathae", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  PassengerPigeon: { name: "Passenger Pigeon", cladeList: ["Ectopistes migratorius", "Columbidae", "Columbiformes", "Columbimorphae", "Neoaves", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  GreatAuk: { name: "Great Auk", cladeList: ["Pinguinus impennis", "Charadriiformes", "Neoaves", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  StellersSeaCow: { name: "Steller's Sea Cow", cladeList: ["Hydrodamalis gigas", "Sirenia", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Quagga: { name: "Quagga", cladeList: ["Equus quagga quagga", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 8: PREHISTORIC BIRDS & AVIALANS
  // =================================================================
  Archaeopteryx: { name: "Archaeopteryx", cladeList: ["Archaeopteryx lithographica", "Avialae", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Titanis: { name: "Titanis", cladeList: ["Titanis walleri", "Cariamiformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Argentavis: { name: "Argentavis", cladeList: ["Argentavis magnificens", "Cathartiformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  HaastsEagle: { name: "Haast's Eagle", cladeList: ["Hieraaetus moorei", "Accipitriformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hesperornis: { name: "Hesperornis", cladeList: ["Hesperornis regalis", "Hesperornithes", "Ornithurae", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Gastornis: { name: "Gastornis", cladeList: ["Gastornis giganteus", "Anseriformes", "Galloanserae", "Neognathae", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Pelagornis: { name: "Pelagornis", cladeList: ["Pelagornis sandersi", "Odontopterygiformes", "Galloanserae", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 9: SYNAPSIDS
  // =================================================================
  Dimetrodon: { name: "Dimetrodon", cladeList: ["Dimetrodon grandis", "Sphenacodontia", "Eupelycosauria", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Gorgonops: { name: "Gorgonops", cladeList: ["Gorgonops torvus", "Gorgonopsidae", "Gorgonopsia", "Theriodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Edaphosaurus: { name: "Edaphosaurus", cladeList: ["Edaphosaurus pogonias", "Edaphosauria", "Eupelycosauria", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Inostrancevia: { name: "Inostrancevia", cladeList: ["Inostrancevia alexandri", "Gorgonopsidae", "Gorgonopsia", "Theriodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Lystrosaurus: { name: "Lystrosaurus", cladeList: ["Lystrosaurus murrayi", "Dicynodontia", "Anomodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Moschops: { name: "Moschops", cladeList: ["Moschops capensis", "Dinocephalia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 10: AMPHIBIANS & EARLY TETRAPODS
  // =================================================================
  Tiktaalik: { name: "Tiktaalik", cladeList: ["Tiktaalik roseae", "Stegocephalia", "Tetrapodomorpha", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Diplocaulus: { name: "Diplocaulus", cladeList: ["Diplocaulus magnicornis", "Nectridea", "Lepospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Eryops: { name: "Eryops", cladeList: ["Eryops megacephalus", "Euskelia", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Koolasuchus: { name: "Koolasuchus", cladeList: ["Koolasuchus cleelandi", "Stereospondyli", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Prionosuchus: { name: "Prionosuchus", cladeList: ["Prionosuchus plummeri", "Stereospondyli", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 11: PREHISTORIC FISH & SHARKS
  // =================================================================
  Dunkleosteus: { name: "Dunkleosteus", cladeList: ["Dunkleosteus terrelli", "Arthrodira", "Placodermi", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Helicoprion: { name: "Helicoprion", cladeList: ["Helicoprion bessonowi", "Holocephali", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Leedsichthys: { name: "Leedsichthys", cladeList: ["Leedsichthys problematicus", "Pachycormiformes", "Actinopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Xiphactinus: { name: "Xiphactinus", cladeList: ["Xiphactinus audax", "Ichthyodectiformes", "Actinopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Stethacanthus: { name: "Stethacanthus", cladeList: ["Stethacanthus altonensis", "Symmoriida", "Holocephali", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Cretoxyrhina: { name: "Cretoxyrhina", cladeList: ["Cretoxyrhina mantelli", "Lamniformes", "Galeomorphii", "Selachimorpha", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Orthacanthus: { name: "Orthacanthus", cladeList: ["Orthacanthus senckenbergianus", "Xenacanthida", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 12: INVERTEBRATES
  // =================================================================
  Trilobite: { name: "Trilobite", cladeList: ["Paradoxides davidis", "Redlichiida", "Trilobita", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Anomalocaris: { name: "Anomalocaris", cladeList: ["Anomalocaris canadensis", "Radiodonta", "Dinocaridida", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Arthropleura: { name: "Arthropleura", cladeList: ["Arthropleura armata", "Arthropleuridea", "Diplopoda", "Myriapoda", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Meganeura: { name: "Meganeura", cladeList: ["Meganeura monyi", "Meganisoptera", "Odonatoptera", "Palaeoptera", "Insecta", "Hexapoda", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Ammonite: { name: "Ammonite", cladeList: ["Ammonoidea", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  SeaScorpion: { name: "Sea Scorpion", cladeList: ["Jaekelopterus rhenaniae", "Eurypterida", "Chelicerata", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hallucigenia: { name: "Hallucigenia", cladeList: ["Hallucigenia sparsa", "Xenusia", "Lobopodia", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Opabinia: { name: "Opabinia", cladeList: ["Opabinia regalis", "Opabiniidae", "Dinocaridida", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Cameroceras: { name: "Cameroceras", cladeList: ["Cameroceras hennepini", "Endocerida", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Belemnite: { name: "Belemnite", cladeList: ["Belemnoidea", "Coleoidea", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] }
};
export const Wiki = {
  "Accipitriformes": "https://en.wikipedia.org/wiki/Accipitriformes",
  "Actinopterygii": "https://en.wikipedia.org/wiki/Actinopterygii",
  "Aenocyon dirus": "https://en.wikipedia.org/wiki/Aenocyon_dirus",
  "Afrotheria": "https://en.wikipedia.org/wiki/Afrotheria",
  "Albertosaurus sarcophagus": "https://en.wikipedia.org/wiki/Albertosaurus_sarcophagus",
  "Allosauridae": "https://en.wikipedia.org/wiki/Allosauridae",
  "Allosauroidea": "https://en.wikipedia.org/wiki/Allosauroidea",
  "Allosaurus fragilis": "https://en.wikipedia.org/wiki/Allosaurus_fragilis",
  "Amargasaurus cazaui": "https://en.wikipedia.org/wiki/Amargasaurus_cazaui",
  "Ammonoidea": "https://en.wikipedia.org/wiki/Ammonoidea",
  "Amniota": "https://en.wikipedia.org/wiki/Amniota",
  "Andrewsarchus mongoliensis": "https://en.wikipedia.org/wiki/Andrewsarchus_mongoliensis",
  "Ankylosauria": "https://en.wikipedia.org/wiki/Ankylosauria",
  "Ankylosauridae": "https://en.wikipedia.org/wiki/Ankylosauridae",
  "Ankylosaurus magniventris": "https://en.wikipedia.org/wiki/Ankylosaurus_magniventris",
  "Anomalocaris canadensis": "https://en.wikipedia.org/wiki/Anomalocaris_canadensis",
  "Anomodontia": "https://en.wikipedia.org/wiki/Anomodontia",
  "Anseriformes": "https://en.wikipedia.org/wiki/Anseriformes",
  "Apatosaurus ajax": "https://en.wikipedia.org/wiki/Apatosaurus_ajax",
  "Archaeopteryx lithographica": "https://en.wikipedia.org/wiki/Archaeopteryx_lithographica",
  "Archosauria": "https://en.wikipedia.org/wiki/Archosauria",
  "Archosauromorpha": "https://en.wikipedia.org/wiki/Archosauromorpha",
  "Argentavis magnificens": "https://en.wikipedia.org/wiki/Argentavis_magnificens",
  "Argentinosaurus huinculensis": "https://en.wikipedia.org/wiki/Argentinosaurus_huinculensis",
  "Arthrodira": "https://en.wikipedia.org/wiki/Arthrodira",
  "Arthropleura armata": "https://en.wikipedia.org/wiki/Arthropleura_armata",
  "Arthropleuridea": "https://en.wikipedia.org/wiki/Arthropleuridea",
  "Arthropoda": "https://en.wikipedia.org/wiki/Arthropoda",
  "Artiodactyla": "https://en.wikipedia.org/wiki/Artiodactyla",
  "Australidelphia": "https://en.wikipedia.org/wiki/Australidelphia",
  "Avemetatarsalia": "https://en.wikipedia.org/wiki/Avemetatarsalia",
  "Avialae": "https://en.wikipedia.org/wiki/Avialae",
  "Aves": "https://en.wikipedia.org/wiki/Aves",
  "Azhdarchidae": "https://en.wikipedia.org/wiki/Azhdarchidae",
  "Azhdarchoidea": "https://en.wikipedia.org/wiki/Azhdarchoidea",
  "Baryonyx walkeri": "https://en.wikipedia.org/wiki/Baryonyx_walkeri",
  "Basilosaurus cetoides": "https://en.wikipedia.org/wiki/Basilosaurus_cetoides",
  "Belemnites": "https://en.wikipedia.org/wiki/Belemnites",
  "Belemnoidea": "https://en.wikipedia.org/wiki/Belemnoidea",
  "Bilateria": "https://en.wikipedia.org/wiki/Bilateria",
  "Brachiosauridae": "https://en.wikipedia.org/wiki/Brachiosauridae",
  "Brachiosaurus altithorax": "https://en.wikipedia.org/wiki/Brachiosaurus_altithorax",
  "Camarasauromorpha": "https://en.wikipedia.org/wiki/Camarasauromorpha",
  "Camarasaurus supremus": "https://en.wikipedia.org/wiki/Camarasaurus_supremus",
  "Carcharaodontosauridae": "https://en.wikipedia.org/wiki/Carcharaodontosauridae",
  "Carcharodontosauridae": "https://en.wikipedia.org/wiki/Carcharodontosauridae",
  "Carnivora": "https://en.wikipedia.org/wiki/Carnivora",
  "Carnotaurus sastrei": "https://en.wikipedia.org/wiki/Carnotaurus_sastrei",
  "Carnosauria": "https://en.wikipedia.org/wiki/Carnosauria",
  "Castorimorpha": "https://en.wikipedia.org/wiki/Castorimorpha",
  "Castoroides ohioensis": "https://en.wikipedia.org/wiki/Castoroides_ohioensis",
  "Cephalopoda": "https://en.wikipedia.org/wiki/Cephalopoda",
  "Ceratosauria": "https://en.wikipedia.org/wiki/Ceratosauria",
  "Ceratosaurus nasicornis": "https://en.wikipedia.org/wiki/Ceratosaurus_nasicornis",
  "Ceratopsia": "https://en.wikipedia.org/wiki/Ceratopsia",
  "Ceratopsidae": "https://en.wikipedia.org/wiki/Ceratopsidae",
  "Cetacea": "https://en.wikipedia.org/wiki/Cetacea",
  "Cetancodontamorpha": "https://en.wikipedia.org/wiki/Cetancodontamorpha",
  "Chelicerata": "https://en.wikipedia.org/wiki/Chelicerata",
  "Chlamyphoridae": "https://en.wikipedia.org/wiki/Chlamyphoridae",
  "Chondrichthyes": "https://en.wikipedia.org/wiki/Chondrichthyes",
  "Chordata": "https://en.wikipedia.org/wiki/Chordata",
  "Coelurosauria": "https://en.wikipedia.org/wiki/Coelurosauria",
  "Coelodonta antiquitatis": "https://en.wikipedia.org/wiki/Coelodonta_antiquitatis",
  "Coleoidea": "https://en.wikipedia.org/wiki/Coleoidea",
  "Colossosauria": "https://en.wikipedia.org/wiki/Colossosauria",
  "Columbidae": "https://en.wikipedia.org/wiki/Columbidae",
  "Columbiformes": "https://en.wikipedia.org/wiki/Columbiformes",
  "Columbimorphae": "https://en.wikipedia.org/wiki/Columbimorphae",
  "Compsognathus longipes": "https://en.wikipedia.org/wiki/Compsognathus_longipes",
  "Craniata": "https://en.wikipedia.org/wiki/Craniata",
  "Cretoxyrhina mantelli": "https://en.wikipedia.org/wiki/Cretoxyrhina_mantelli",
  "Cryolophosaurus ellioti": "https://en.wikipedia.org/wiki/Cryolophosaurus_ellioti",
  "Cynodontia": "https://en.wikipedia.org/wiki/Cynodontia",
  "Daeodon shoshonensis": "https://en.wikipedia.org/wiki/Daeodon_shoshonensis",
  "Dasyuromorphia": "https://en.wikipedia.org/wiki/Dasyuromorphia",
  "Deinonychus antirrhopus": "https://en.wikipedia.org/wiki/Deinonychus_antirrhopus",
  "Deuterostomia": "https://en.wikipedia.org/wiki/Deuterostomia",
  "Diapsida": "https://en.wikipedia.org/wiki/Diapsida",
  "Dicynodontia": "https://en.wikipedia.org/wiki/Dicynodontia",
  "Dilophosaurus wetherilli": "https://en.wikipedia.org/wiki/Dilophosaurus_wetherilli",
  "Dinocaridida": "https://en.wikipedia.org/wiki/Dinocaridida",
  "Dinornis robustus": "https://en.wikipedia.org/wiki/Dinornis_robustus",
  "Dinornithiformes": "https://en.wikipedia.org/wiki/Dinornithiformes",
  "Dinosauria": "https://en.wikipedia.org/wiki/Dinosauria",
  "Diplocaulus magnicornis": "https://en.wikipedia.org/wiki/Diplocaulus_magnicornis",
  "Diplodocidae": "https://en.wikipedia.org/wiki/Diplodocidae",
  "Diplodocoidea": "https://en.wikipedia.org/wiki/Diplodocoidea",
  "Diplodocus carnegii": "https://en.wikipedia.org/wiki/Diplodocus_carnegii",
  "Diprotodon optatum": "https://en.wikipedia.org/wiki/Diprotodon_optatum",
  "Diprotodontia": "https://en.wikipedia.org/wiki/Diprotodontia",
  "Dire Wolf": "https://en.wikipedia.org/wiki/Dire_Wolf",
  "Dromaeosauridae": "https://en.wikipedia.org/wiki/Dromaeosauridae",
  "Dunkleosteus terrelli": "https://en.wikipedia.org/wiki/Dunkleosteus_terrelli",
  "Ecdysozoa": "https://en.wikipedia.org/wiki/Ecdysozoa",
  "Edaphosauria": "https://en.wikipedia.org/wiki/Edaphosauria",
  "Edaphosaurus pogonias": "https://en.wikipedia.org/wiki/Edaphosaurus_pogonias",
  "Edmontosaurus annectens": "https://en.wikipedia.org/wiki/Edmontosaurus_annectens",
  "Elasmosaurus platyurus": "https://en.wikipedia.org/wiki/Elasmosaurus_platyurus",
  "Elasmobranchii": "https://en.wikipedia.org/wiki/Elasmobranchii",
  "Endocerida": "https://en.wikipedia.org/wiki/Endocerida",
  "Ectopistes migratorius": "https://en.wikipedia.org/wiki/Ectopistes_migratorius",
  "Eumaniraptora": "https://en.wikipedia.org/wiki/Eumaniraptora",
  "Eumetazoa": "https://en.wikipedia.org/wiki/Eumetazoa",
  "Euarchontoglires": "https://en.wikipedia.org/wiki/Euarchontoglires",
  "Eupelycosauria": "https://en.wikipedia.org/wiki/Eupelycosauria",
  "Eurypterida": "https://en.wikipedia.org/wiki/Eurypterida",
  "Eurypoda": "https://en.wikipedia.org/wiki/Eurypoda",
  "Eusauropoda": "https://en.wikipedia.org/wiki/Eusauropoda",
  "Euskelia": "https://en.wikipedia.org/wiki/Euskelia",
  "Euoplocephalus tutus": "https://en.wikipedia.org/wiki/Euoplocephalus_tutus",
  "Ferae": "https://en.wikipedia.org/wiki/Ferae",
  "Feliformia": "https://en.wikipedia.org/wiki/Feliformia",
  "Folivora": "https://en.wikipedia.org/wiki/Folivora",
  "Galeomorphii": "https://en.wikipedia.org/wiki/Galeomorphii",
  "Gallimimus bullatus": "https://en.wikipedia.org/wiki/Gallimimus_bullatus",
  "Galloanserae": "https://en.wikipedia.org/wiki/Galloanserae",
  "Gastornis giganteus": "https://en.wikipedia.org/wiki/Gastornis_giganteus",
  "Giganotosaurus carolinii": "https://en.wikipedia.org/wiki/Giganotosaurus_carolinii",
  "Giraffatitan brancai": "https://en.wikipedia.org/wiki/Giraffatitan_brancai",
  "Gnathostomata": "https://en.wikipedia.org/wiki/Gnathostomata",
  "Gorgonops torvus": "https://en.wikipedia.org/wiki/Gorgonops_torvus",
  "Gorgonopsia": "https://en.wikipedia.org/wiki/Gorgonopsia",
  "Gorgonopsidae": "https://en.wikipedia.org/wiki/Gorgonopsidae",
  "Great Auk": "https://en.wikipedia.org/wiki/Great_Auk",
  "Hallucigenia sparsa": "https://en.wikipedia.org/wiki/Hallucigenia_sparsa",
  "Hadrosauridae": "https://en.wikipedia.org/wiki/Hadrosauridae",
  "Hadrosauroidea": "https://en.wikipedia.org/wiki/Hadrosauroidea",
  "HaastsEagle": "https://en.wikipedia.org/wiki/HaastsEagle",
  "Hatzegopteryx thambema": "https://en.wikipedia.org/wiki/Hatzegopteryx_thambema",
  "Helicoprion bessonowi": "https://en.wikipedia.org/wiki/Helicoprion_bessonowi",
  "Hesperornis regalis": "https://en.wikipedia.org/wiki/Hesperornis_regalis",
  "Hesperornithes": "https://en.wikipedia.org/wiki/Hesperornithes",
  "Hexapoda": "https://en.wikipedia.org/wiki/Hexapoda",
  "Hieraaetus moorei": "https://en.wikipedia.org/wiki/Hieraaetus_moorei",
  "Holocephali": "https://en.wikipedia.org/wiki/Holocephali",
  "Hyaenodonta": "https://en.wikipedia.org/wiki/Hyaenodonta",
  "Hyaenodon horridus": "https://en.wikipedia.org/wiki/Hyaenodon_horridus",
  "Hypsilophodon foxii": "https://en.wikipedia.org/wiki/Hypsilophodon_foxii",
  "Ichthyodectiformes": "https://en.wikipedia.org/wiki/Ichthyodectiformes",
  "Ichthyosauria": "https://en.wikipedia.org/wiki/Ichthyosauria",
  "Ichthyosauromorpha": "https://en.wikipedia.org/wiki/Ichthyosauromorpha",
  "Ichthyosaurus communis": "https://en.wikipedia.org/wiki/Ichthyosaurus_communis",
  "Iguanodon bernissartensis": "https://en.wikipedia.org/wiki/Iguanodon_bernissartensis",
  "Iguanodontia": "https://en.wikipedia.org/wiki/Iguanodontia",
  "Inostrancevia alexandri": "https://en.wikipedia.org/wiki/Inostrancevia_alexandri",
  "Insecta": "https://en.wikipedia.org/wiki/Insecta",
  "Jaekelopterus rhenaniae": "https://en.wikipedia.org/wiki/Jaekelopterus_rhenaniae",
  "Kentrosaurus aethiopicus": "https://en.wikipedia.org/wiki/Kentrosaurus_aethiopicus",
  "Koolasuchus cleelandi": "https://en.wikipedia.org/wiki/Koolasuchus_cleelandi",
  "Kronosaurus queenslandicus": "https://en.wikipedia.org/wiki/Kronosaurus_queenslandicus",
  "Lamniformes": "https://en.wikipedia.org/wiki/Lamniformes",
  "Laurasiatheria": "https://en.wikipedia.org/wiki/Laurasiatheria",
  "Leedsichthys problematicus": "https://en.wikipedia.org/wiki/Leedsichthys_problematicus",
  "Lepidosauria": "https://en.wikipedia.org/wiki/Lepidosauria",
  "Lepospondyli": "https://en.wikipedia.org/wiki/Lepospondyli",
  "Litopterna": "https://en.wikipedia.org/wiki/Litopterna",
  "Liopleurodon ferox": "https://en.wikipedia.org/wiki/Liopleurodon_ferox",
  "Lobopodia": "https://en.wikipedia.org/wiki/Lobopodia",
  "Lophotrochozoa": "https://en.wikipedia.org/wiki/Lophotrochozoa",
  "Lystrosaurus murrayi": "https://en.wikipedia.org/wiki/Lystrosaurus_murrayi",
  "Macrauchenia patachonica": "https://en.wikipedia.org/wiki/Macrauchenia_patachonica",
  "Macronaria": "https://en.wikipedia.org/wiki/Macronaria",
  "Macropodiformes": "https://en.wikipedia.org/wiki/Macropodiformes",
  "Maiasaura peeblesorum": "https://en.wikipedia.org/wiki/Maiasaura_peeblesorum",
  "Maniraptora": "https://en.wikipedia.org/wiki/Maniraptora",
  "Maniraptoriformes": "https://en.wikipedia.org/wiki/Maniraptoriformes",
  "Marginocephalia": "https://en.wikipedia.org/wiki/Marginocephalia",
  "Marsupialia": "https://en.wikipedia.org/wiki/Marsupialia",
  "Mastodon": "https://en.wikipedia.org/wiki/Mastodon",
  "Mammut americanum": "https://en.wikipedia.org/wiki/Mammut_americanum",
  "Mammalia": "https://en.wikipedia.org/wiki/Mammalia",
  "Mammaliaformes": "https://en.wikipedia.org/wiki/Mammaliaformes",
  "Mammuthus primigenius": "https://en.wikipedia.org/wiki/Mammuthus_primigenius",
  "Mamenchisaurus constructus": "https://en.wikipedia.org/wiki/Mamenchisaurus_constructus",
  "Meganisoptera": "https://en.wikipedia.org/wiki/Meganisoptera",
  "Megalosauroidea": "https://en.wikipedia.org/wiki/Megalosauroidea",
  "Meganeura monyi": "https://en.wikipedia.org/wiki/Meganeura_monyi",
  "Megaloceros giganteus": "https://en.wikipedia.org/wiki/Megaloceros_giganteus",
  "Megatherium americanum": "https://en.wikipedia.org/wiki/Megatherium_americanum",
  "Meridiungulata": "https://en.wikipedia.org/wiki/Meridiungulata",
  "Metatheria": "https://en.wikipedia.org/wiki/Metatheria",
  "Metazoa": "https://en.wikipedia.org/wiki/Metazoa",
  "Mollusca": "https://en.wikipedia.org/wiki/Mollusca",
  "Mosasauridae": "https://en.wikipedia.org/wiki/Mosasauridae",
  "Mosasauroidea": "https://en.wikipedia.org/wiki/Mosasauroidea",
  "Mosasaurus hoffmannii": "https://en.wikipedia.org/wiki/Mosasaurus_hoffmannii",
  "Moschops capensis": "https://en.wikipedia.org/wiki/Moschops_capensis",
  "Neoaves": "https://en.wikipedia.org/wiki/Neoaves",
  "Neognathae": "https://en.wikipedia.org/wiki/Neognathae",
  "Neosauropoda": "https://en.wikipedia.org/wiki/Neosauropoda",
  "Nectridea": "https://en.wikipedia.org/wiki/Nectridea",
  "Neotheropoda": "https://en.wikipedia.org/wiki/Neotheropoda",
  "Odontopterygiformes": "https://en.wikipedia.org/wiki/Odontopterygiformes",
  "Odonatoptera": "https://en.wikipedia.org/wiki/Odonatoptera",
  "Opabinia regalis": "https://en.wikipedia.org/wiki/Opabinia_regalis",
  "Opabiniidae": "https://en.wikipedia.org/wiki/Opabiniidae",
  "Ornithischia": "https://en.wikipedia.org/wiki/Ornithischia",
  "Ornithodira": "https://en.wikipedia.org/wiki/Ornithodira",
  "Ornithopoda": "https://en.wikipedia.org/wiki/Ornithopoda",
  "Ornithurae": "https://en.wikipedia.org/wiki/Ornithurae",
  "Orthacanthus senckenbergianus": "https://en.wikipedia.org/wiki/Orthacanthus_senckenbergianus",
  "Osteichthyes": "https://en.wikipedia.org/wiki/Osteichthyes",
  "Otodus megalodon": "https://en.wikipedia.org/wiki/Otodus_megalodon",
  "Oviraptor philoceratops": "https://en.wikipedia.org/wiki/Oviraptor_philoceratops",
  "Pachycormiformes": "https://en.wikipedia.org/wiki/Pachycormiformes",
  "Pachycephalosaurus wyomingensis": "https://en.wikipedia.org/wiki/Pachycephalosaurus_wyomingensis",
  "Paenungulata": "https://en.wikipedia.org/wiki/Paenungulata",
  "Palaeognathae": "https://en.wikipedia.org/wiki/Palaeognathae",
  "Palaeoptera": "https://en.wikipedia.org/wiki/Palaeoptera",
  "Panarthropoda": "https://en.wikipedia.org/wiki/Panarthropoda",
  "Paraceratherium transouralicum": "https://en.wikipedia.org/wiki/Paraceratherium_transouralicum",
  "Paradoxides davidis": "https://en.wikipedia.org/wiki/Paradoxides_davidis",
  "Paraves": "https://en.wikipedia.org/wiki/Paraves",
  "Parasaurolophus walkeri": "https://en.wikipedia.org/wiki/Parasaurolophus_walkeri",
  "Patagotitan mayorum": "https://en.wikipedia.org/wiki/Patagotitan_mayorum",
  "Pelagiceti": "https://en.wikipedia.org/wiki/Pelagiceti",
  "Pelagornis sandersi": "https://en.wikipedia.org/wiki/Pelagornis_sandersi",
  "Perissodactyla": "https://en.wikipedia.org/wiki/Perissodactyla",
  "Pinguinus impennis": "https://en.wikipedia.org/wiki/Pinguinus_impennis",
  "Pilosa": "https://en.wikipedia.org/wiki/Pilosa",
  "Placentalia": "https://en.wikipedia.org/wiki/Placentalia",
  "Placodermi": "https://en.wikipedia.org/wiki/Placodermi",
  "Plesiosauria": "https://en.wikipedia.org/wiki/Plesiosauria",
  "Plesiosauroidea": "https://en.wikipedia.org/wiki/Plesiosauroidea",
  "Pliosauridae": "https://en.wikipedia.org/wiki/Pliosauridae",
  "Pliosauroidea": "https://en.wikipedia.org/wiki/Pliosauroidea",
  "Prionosuchus plummeri": "https://en.wikipedia.org/wiki/Prionosuchus_plummeri",
  "Procoptodon goliah": "https://en.wikipedia.org/wiki/Procoptodon_goliah",
  "Protoceratops andrewsi": "https://en.wikipedia.org/wiki/Protoceratops_andrewsi",
  "Protostomia": "https://en.wikipedia.org/wiki/Protostomia",
  "Psittacosaurus mongoliensis": "https://en.wikipedia.org/wiki/Psittacosaurus_mongoliensis",
  "Pteranodon longiceps": "https://en.wikipedia.org/wiki/Pteranodon_longiceps",
  "Pterodactyloidea": "https://en.wikipedia.org/wiki/Pterodactyloidea",
  "Pterosauria": "https://en.wikipedia.org/wiki/Pterosauria",
  "Quagga": "https://en.wikipedia.org/wiki/Quagga",
  "Quetzalcoatlus northropi": "https://en.wikipedia.org/wiki/Quetzalcoatlus_northropi",
  "Radiodonta": "https://en.wikipedia.org/wiki/Radiodonta",
  "Raphus cucullatus": "https://en.wikipedia.org/wiki/Raphus_cucullatus",
  "Rhamphorhynchus muensteri": "https://en.wikipedia.org/wiki/Rhamphorhynchus_muensteri",
  "Rodentia": "https://en.wikipedia.org/wiki/Rodentia",
  "Ruminantia": "https://en.wikipedia.org/wiki/Ruminantia",
  "Sarcopterygii": "https://en.wikipedia.org/wiki/Sarcopterygii",
  "Sauria": "https://en.wikipedia.org/wiki/Sauria",
  "Saurischia": "https://en.wikipedia.org/wiki/Saurischia",
  "Saurolophinae": "https://en.wikipedia.org/wiki/Saurolophinae",
  "Sauropsida": "https://en.wikipedia.org/wiki/Sauropsida",
  "Sauropoda": "https://en.wikipedia.org/wiki/Sauropoda",
  "Sauropterygia": "https://en.wikipedia.org/wiki/Sauropterygia",
  "Selachimorpha": "https://en.wikipedia.org/wiki/Selachimorpha",
  "Sphenacodontia": "https://en.wikipedia.org/wiki/Sphenacodontia",
  "Spinosauridae": "https://en.wikipedia.org/wiki/Spinosauridae",
  "Spinosaurus aegyptiacus": "https://en.wikipedia.org/wiki/Spinosaurus_aegyptiacus",
  "Stegocephalia": "https://en.wikipedia.org/wiki/Stegocephalia",
  "Stegosauridae": "https://en.wikipedia.org/wiki/Stegosauridae",
  "Stegosauria": "https://en.wikipedia.org/wiki/Stegosauria",
  "Stegosaurus stenops": "https://en.wikipedia.org/wiki/Stegosaurus_stenops",
  "Stethacanthus altonensis": "https://en.wikipedia.org/wiki/Stethacanthus_altonensis",
  "Stereospondyli": "https://en.wikipedia.org/wiki/Stereospondyli",
  "Styracosaurus albertensis": "https://en.wikipedia.org/wiki/Styracosaurus_albertensis",
  "Squamata": "https://en.wikipedia.org/wiki/Squamata",
  "Synapsida": "https://en.wikipedia.org/wiki/Synapsida",
  "Symmoriida": "https://en.wikipedia.org/wiki/Symmoriida",
  "Tapejara wellnhoferi": "https://en.wikipedia.org/wiki/Tapejara_wellnhoferi",
  "TasmanianTiger": "https://en.wikipedia.org/wiki/TasmanianTiger",
  "Tetanurae": "https://en.wikipedia.org/wiki/Tetanurae",
  "Tetrapoda": "https://en.wikipedia.org/wiki/Tetrapoda",
  "Tetrapodomorpha": "https://en.wikipedia.org/wiki/Tetrapodomorpha",
  "Therapsida": "https://en.wikipedia.org/wiki/Therapsida",
  "Theriodontia": "https://en.wikipedia.org/wiki/Theriodontia",
  "Therizinosaurus cheloniformis": "https://en.wikipedia.org/wiki/Therizinosaurus_cheloniformis",
  "Theropoda": "https://en.wikipedia.org/wiki/Theropoda",
  "Thylacoleo carnifex": "https://en.wikipedia.org/wiki/Thylacoleo_carnifex",
  "Thylacinus cynocephalus": "https://en.wikipedia.org/wiki/Thylacinus_cynocephalus",
  "Thyreophora": "https://en.wikipedia.org/wiki/Thyreophora",
  "Tiktaalik roseae": "https://en.wikipedia.org/wiki/Tiktaalik_roseae",
  "Titanis walleri": "https://en.wikipedia.org/wiki/Titanis_walleri",
  "Titanosauria": "https://en.wikipedia.org/wiki/Titanosauria",
  "Triceratops horridus": "https://en.wikipedia.org/wiki/Triceratops_horridus",
  "Trilobita": "https://en.wikipedia.org/wiki/Trilobita",
  "Troodon formosus": "https://en.wikipedia.org/wiki/Troodon_formosus",
  "Tylosaurus proriger": "https://en.wikipedia.org/wiki/Tylosaurus_proriger",
  "Tyrannosauridae": "https://en.wikipedia.org/wiki/Tyrannosauridae",
  "Tyrannosauroidea": "https://en.wikipedia.org/wiki/Tyrannosauroidea",
  "Tyrannosaurus rex": "https://en.wikipedia.org/wiki/Tyrannosaurus_rex",
  "Ursus spelaeus": "https://en.wikipedia.org/wiki/Ursus_spelaeus",
  "Velociraptor mongoliensis": "https://en.wikipedia.org/wiki/Velociraptor_mongoliensis",
  "Vertebrata": "https://en.wikipedia.org/wiki/Vertebrata",
  "Vombatiformes": "https://en.wikipedia.org/wiki/Vombatiformes",
  "Xenacanthida": "https://en.wikipedia.org/wiki/Xenacanthida",
  "Xenarthra": "https://en.wikipedia.org/wiki/Xenarthra",
  "Xenusia": "https://en.wikipedia.org/wiki/Xenusia",
  "Xiphactinus audax": "https://en.wikipedia.org/wiki/Xiphactinus_audax"
};
