export const Metazoa = {
  // =================================================================
  // FAMOUS EXAMPLES (Theropods & Sharks)
  // =================================================================
  TyrannosaurusRex: { name: "Tyrannosaurus Rex", cladeList: ["Tyrannosaurus rex", "Tyrannosaurinae", "Tyrannosauridae", "Tyrannosauroidea", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Archosauromorpha", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Megalodon: { name: "Megalodon", cladeList: ["Otodus megalodon", "Otodontidae", "Lamniformes", "Galeomorphii", "Selachimorpha", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },

  // =================================================================
  // GROUP 1: THEROPOD DINOSAURS
  // =================================================================
  Velociraptor: { name: "Velociraptor", cladeList: ["Velociraptor mongoliensis", "Velociraptorinae", "Dromaeosauridae", "Eumaniraptora", "Paraves", "Maniraptora", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Spinosaurus: { name: "Spinosaurus", cladeList: ["Spinosaurus aegyptiacus", "Spinosaurinae", "Spinosauridae", "Megalosauroidea", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Allosaurus: { name: "Allosaurus", cladeList: ["Allosaurus fragilis", "Allosaurinae", "Allosauridae", "Allosauroidea", "Carnosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Giganotosaurus: { name: "Giganotosaurus", cladeList: ["Giganotosaurus carolinii", "Carcharodontosaurinae", "Carcharodontosauridae", "Allosauroidea", "Carnosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Dilophosaurus: { name: "Dilophosaurus", cladeList: ["Dilophosaurus wetherilli", "Dilophosauridae", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Carnotaurus: { name: "Carnotaurus", cladeList: ["Carnotaurus sastrei", "Brachyrostra", "Abelisauridae", "Abelisauroidea", "Ceratosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Ceratosaurus: { name: "Ceratosaurus", cladeList: ["Ceratosaurus nasicornis", "Ceratosauridae", "Ceratosauria", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Deinonychus: { name: "Deinonychus", cladeList: ["Deinonychus antirrhopus", "Dromaeosaurinae", "Dromaeosauridae", "Eumaniraptora", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Compsognathus: { name: "Compsognathus", cladeList: ["Compsognathus longipes", "Compsognathidae", "Compsognathoidea", "Coelurosauria", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Gallimimus: { name: "Gallimimus", cladeList: ["Gallimimus bullatus", "Ornithomimidae", "Ornithomimosauria", "Maniraptoriformes", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Therizinosaurus: { name: "Therizinosaurus", cladeList: ["Therizinosaurus cheloniformis", "Therizinosauridae", "Therizinosauria", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Baryonyx: { name: "Baryonyx", cladeList: ["Baryonyx walkeri", "Baryonychinae", "Spinosauridae", "Megalosauroidea", "Tetanurae", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Albertosaurus: { name: "Albertosaurus", cladeList: ["Albertosaurus sarcophagus", "Albertosaurinae", "Tyrannosauridae", "Tyrannosauroidea", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Oviraptor: { name: "Oviraptor", cladeList: ["Oviraptor philoceratops", "Oviraptoridae", "Oviraptorosauria", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Troodon: { name: "Troodon", cladeList: ["Troodon formosus", "Troodontidae", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Cryolophosaurus: { name: "Cryolophosaurus", cladeList: ["Cryolophosaurus ellioti", "Tetanurae", "Neotheropoda", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 2: SAUROPODS
  // =================================================================
  Brachiosaurus: { name: "Brachiosaurus", cladeList: ["Brachiosaurus altithorax", "Brachiosauridae", "Macronaria", "Camarasauromorpha", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Diplodocus: { name: "Diplodocus", cladeList: ["Diplodocus carnegii", "Diplodocinae", "Diplodocidae", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Apatosaurus: { name: "Apatosaurus", cladeList: ["Apatosaurus ajax", "Apatosaurinae", "Diplodocidae", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Argentinosaurus: { name: "Argentinosaurus", cladeList: ["Argentinosaurus huinculensis", "Antarctosauridae", "Colossosauria", "Titanosauria", "Macronaria", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Amargasaurus: { name: "Amargasaurus", cladeList: ["Amargasaurus cazaui", "Dicraeosauridae", "Diplodocoidea", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Camarasaurus: { name: "Camarasaurus", cladeList: ["Camarasaurus supremus", "Camarasauridae", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Giraffatitan: { name: "Giraffatitan", cladeList: ["Giraffatitan brancai", "Brachiosauridae", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Dreadnoughtus: { name: "Dreadnoughtus", cladeList: ["Dreadnoughtus schrani", "Titanosauria", "Macronaria", "Neosauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Patagotitan: { name: "Patagotitan", cladeList: ["Patagotitan mayorum", "Lognkosauria", "Colossosauria", "Titanosauria", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Mamenchisaurus: { name: "Mamenchisaurus", cladeList: ["Mamenchisaurus constructus", "Mamenchisauridae", "Eusauropoda", "Sauropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 3: ORNITHISCHIAN DINOSAURS
  // =================================================================
  Triceratops: { name: "Triceratops", cladeList: ["Triceratops horridus", "Chasmosaurinae", "Ceratopsidae", "Ceratopsia", "Marginocephalia", "Cerapoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Stegosaurus: { name: "Stegosaurus", cladeList: ["Stegosaurus stenops", "Stegosauridae", "Stegosauria", "Eurypoda", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Ankylosaurus: { name: "Ankylosaurus", cladeList: ["Ankylosaurus magniventris", "Ankylosaurinae", "Ankylosauridae", "Ankylosauria", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Parasaurolophus: { name: "Parasaurolophus", cladeList: ["Parasaurolophus walkeri", "Lambeosaurinae", "Hadrosauridae", "Hadrosauroidea", "Iguanodontia", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Iguanodon: { name: "Iguanodon", cladeList: ["Iguanodon bernissartensis", "Iguanodontidae", "Ankylopollexia", "Iguanodontia", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Pachycephalosaurus: { name: "Pachycephalosaurus", cladeList: ["Pachycephalosaurus wyomingensis", "Pachycephalosauridae", "Pachycephalosauria", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Styracosaurus: { name: "Styracosaurus", cladeList: ["Styracosaurus albertensis", "Centrosaurinae", "Ceratopsidae", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Protoceratops: { name: "Protoceratops", cladeList: ["Protoceratops andrewsi", "Protoceratopsidae", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Edmontosaurus: { name: "Edmontosaurus", cladeList: ["Edmontosaurus annectens", "Saurolophinae", "Hadrosauridae", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Kentrosaurus: { name: "Kentrosaurus", cladeList: ["Kentrosaurus aethiopicus", "Stegosauridae", "Stegosauria", "Thyreophora", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Maiasaura: { name: "Maiasaura", cladeList: ["Maiasaura peeblesorum", "Saurolophinae", "Hadrosauridae", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Euoplocephalus: { name: "Euoplocephalus", cladeList: ["Euoplocephalus tutus", "Ankylosaurinae", "Ankylosauridae", "Ankylosauria", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Psittacosaurus: { name: "Psittacosaurus", cladeList: ["Psittacosaurus mongoliensis", "Psittacosauridae", "Ceratopsia", "Marginocephalia", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Hypsilophodon: { name: "Hypsilophodon", cladeList: ["Hypsilophodon foxii", "Hypsilophodontidae", "Ornithopoda", "Ornithischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 4: PTEROSAURS
  // =================================================================
  Pteranodon: { name: "Pteranodon", cladeList: ["Pteranodon longiceps", "Pteranodontidae", "Pteranodontoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Avemetatarsalia", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Quetzalcoatlus: { name: "Quetzalcoatlus", cladeList: ["Quetzalcoatlus northropi", "Azhdarchidae", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Dimorphodon: { name: "Dimorphodon", cladeList: ["Dimorphodon macronyx", "Dimorphodontidae", "Macronychoptera", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Rhamphorhynchus: { name: "Rhamphorhynchus", cladeList: ["Rhamphorhynchus muensteri", "Rhamphorhynchidae", "Rhamphorhynchoidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Tapejara: { name: "Tapejara", cladeList: ["Tapejara wellnhoferi", "Tapejaridae", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Hatzegopteryx: { name: "Hatzegopteryx", cladeList: ["Hatzegopteryx thambema", "Azhdarchidae", "Azhdarchoidea", "Pterodactyloidea", "Pterosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 5: MARINE REPTILES
  // =================================================================
  Mosasaurus: { name: "Mosasaurus", cladeList: ["Mosasaurus hoffmannii", "Mosasaurinae", "Mosasauridae", "Mosasauroidea", "Squamata", "Lepidosauria", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Metazoa"] },
  Plesiosaurus: { name: "Plesiosaurus", cladeList: ["Plesiosaurus dolichodeirus", "Plesiosauridae", "Plesiosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Ichthyosaurus: { name: "Ichthyosaurus", cladeList: ["Ichthyosaurus communis", "Ichthyosauridae", "Ichthyosauria", "Ichthyosauromorpha", "Diapsida", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Elasmosaurus: { name: "Elasmosaurus", cladeList: ["Elasmosaurus platyurus", "Elasmosauridae", "Plesiosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Liopleurodon: { name: "Liopleurodon", cladeList: ["Liopleurodon ferox", "Pliosauridae", "Pliosauroidea", "Plesiosauria", "Sauropterygia", "Sauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Kronosaurus: { name: "Kronosaurus", cladeList: ["Kronosaurus queenslandicus", "Brachaucheninae", "Pliosauridae", "Pliosauroidea", "Plesiosauria", "Sauropterygia", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Tylosaurus: { name: "Tylosaurus", cladeList: ["Tylosaurus proriger", "Tylosaurinae", "Mosasauridae", "Mosasauroidea", "Squamata", "Lepidosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Shonisaurus: { name: "Shonisaurus", cladeList: ["Shonisaurus popularis", "Shastasauridae", "Ichthyosauria", "Ichthyosauromorpha", "Diapsida", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 6: EXTINCT MAMMALS
  // =================================================================
  WoollyMammoth: { name: "Woolly Mammoth", cladeList: ["Mammuthus primigenius", "Elephantidae", "Proboscidea", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Mammaliaformes", "Cynodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Smilodon: { name: "Smilodon", cladeList: ["Smilodon fatalis", "Machairodontinae", "Felidae", "Feliformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  WoollyRhino: { name: "Woolly Rhino", cladeList: ["Coelodonta antiquitatis", "Rhinocerotidae", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Megatherium: { name: "Megatherium", cladeList: ["Megatherium americanum", "Megatheriidae", "Folivora", "Pilosa", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Cynodontia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Paraceratherium: { name: "Paraceratherium", cladeList: ["Paraceratherium transouralicum", "Paraceratheriidae", "Rhinocerotoidea", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  DireWolf: { name: "Dire Wolf", cladeList: ["Aenocyon dirus", "Caninae", "Canidae", "Caniformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Glyptodon: { name: "Glyptodon", cladeList: ["Glyptodon clavipes", "Glyptodontinae", "Chlamyphoridae", "Cingulata", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Andrewsarchus: { name: "Andrewsarchus", cladeList: ["Andrewsarchus mongoliensis", "Andrewsarchidae", "Cetancodontamorpha", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Daeodon: { name: "Daeodon", cladeList: ["Daeodon shoshonensis", "Entelodontidae", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Hyaenodon: { name: "Hyaenodon", cladeList: ["Hyaenodon horridus", "Hyaenodontidae", "Hyaenodonta", "Ferae", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  CaveBear: { name: "Cave Bear", cladeList: ["Ursus spelaeus", "Ursidae", "Caniformia", "Carnivora", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  IrishElk: { name: "Irish Elk", cladeList: ["Megaloceros giganteus", "Cervidae", "Ruminantia", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Diprotodon: { name: "Diprotodon", cladeList: ["Diprotodon optatum", "Diprotodontidae", "Vombatiformes", "Diprotodontia", "Australidelphia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Thylacoleo: { name: "Thylacoleo", cladeList: ["Thylacoleo carnifex", "Thylacoleonidae", "Vombatiformes", "Diprotodontia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Procoptodon: { name: "Procoptodon", cladeList: ["Procoptodon goliah", "Sthenurinae", "Macropodidae", "Macropodiformes", "Diprotodontia", "Marsupialia", "Metatheria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Mastodon: { name: "Mastodon", cladeList: ["Mammut americanum", "Mammutidae", "Proboscidea", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Basilosaurus: { name: "Basilosaurus", cladeList: ["Basilosaurus cetoides", "Basilosauridae", "Pelagiceti", "Cetacea", "Artiodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  GiantBeaver: { name: "Giant Beaver", cladeList: ["Castoroides ohioensis", "Castoridae", "Castorimorpha", "Rodentia", "Euarchontoglires", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Macrauchenia: { name: "Macrauchenia", cladeList: ["Macrauchenia patachonica", "Macraucheniidae", "Litopterna", "Meridiungulata", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Doedicurus: { name: "Doedicurus", cladeList: ["Doedicurus clavicaudatus", "Glyptodontinae", "Chlamyphoridae", "Cingulata", "Xenarthra", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 7: RECENTLY EXTINCT
  // =================================================================
  Dodo: { name: "Dodo", cladeList: ["Raphus cucullatus", "Columbidae", "Columbiformes", "Columbimorphae", "Neoaves", "Neognathae", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  TasmanianTiger: { name: "Tasmanian Tiger", cladeList: ["Thylacinus cynocephalus", "Thylacinidae", "Dasyuromorphia", "Australidelphia", "Marsupialia", "Metatheria", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Moa: { name: "Moa", cladeList: ["Dinornis robustus", "Dinornithidae", "Dinornithiformes", "Palaeognathae", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  PassengerPigeon: { name: "Passenger Pigeon", cladeList: ["Ectopistes migratorius", "Columbidae", "Columbiformes", "Columbimorphae", "Neoaves", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  GreatAuk: { name: "Great Auk", cladeList: ["Pinguinus impennis", "Alcidae", "Charadriiformes", "Neoaves", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  StellersSeaCow: { name: "Steller's Sea Cow", cladeList: ["Hydrodamalis gigas", "Dugongidae", "Sirenia", "Paenungulata", "Afrotheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Quagga: { name: "Quagga", cladeList: ["Equus quagga quagga", "Equidae", "Perissodactyla", "Laurasiatheria", "Placentalia", "Theria", "Mammalia", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 8: PREHISTORIC BIRDS & AVIALANS
  // =================================================================
  Archaeopteryx: { name: "Archaeopteryx", cladeList: ["Archaeopteryx lithographica", "Archaeopterygidae", "Avialae", "Paraves", "Maniraptora", "Coelurosauria", "Theropoda", "Saurischia", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Titanis: { name: "Titanis", cladeList: ["Titanis walleri", "Phorusrhacidae", "Cariamiformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Argentavis: { name: "Argentavis", cladeList: ["Argentavis magnificens", "Teratornithidae", "Cathartiformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  HaastsEagle: { name: "Haast's Eagle", cladeList: ["Hieraaetus moorei", "Accipitridae", "Accipitriformes", "Neoaves", "Aves", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Hesperornis: { name: "Hesperornis", cladeList: ["Hesperornis regalis", "Hesperornithidae", "Hesperornithes", "Ornithurae", "Avialae", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Gastornis: { name: "Gastornis", cladeList: ["Gastornis giganteus", "Gastornithidae", "Anseriformes", "Galloanserae", "Neognathae", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Pelagornis: { name: "Pelagornis", cladeList: ["Pelagornis sandersi", "Pelagornithidae", "Odontopterygiformes", "Galloanserae", "Aves", "Theropoda", "Dinosauria", "Ornithodira", "Archosauria", "Sauropsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 9: SYNAPSIDS
  // =================================================================
  Dimetrodon: { name: "Dimetrodon", cladeList: ["Dimetrodon grandis", "Sphenacodontidae", "Sphenacodontia", "Eupelycosauria", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Gorgonops: { name: "Gorgonops", cladeList: ["Gorgonops torvus", "Gorgonopsidae", "Gorgonopsia", "Theriodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Edaphosaurus: { name: "Edaphosaurus", cladeList: ["Edaphosaurus pogonias", "Edaphosauridae", "Edaphosauria", "Eupelycosauria", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Inostrancevia: { name: "Inostrancevia", cladeList: ["Inostrancevia alexandri", "Gorgonopsidae", "Gorgonopsia", "Theriodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Lystrosaurus: { name: "Lystrosaurus", cladeList: ["Lystrosaurus murrayi", "Lystrosauridae", "Dicynodontia", "Anomodontia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Moschops: { name: "Moschops", cladeList: ["Moschops capensis", "Tapinocephalidae", "Dinocephalia", "Therapsida", "Synapsida", "Amniota", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 10: AMPHIBIANS & EARLY TETRAPODS
  // =================================================================
  Tiktaalik: { name: "Tiktaalik", cladeList: ["Tiktaalik roseae", "Stegocephalia", "Tetrapodomorpha", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Diplocaulus: { name: "Diplocaulus", cladeList: ["Diplocaulus magnicornis", "Keraterpetontidae", "Nectridea", "Lepospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Eryops: { name: "Eryops", cladeList: ["Eryops megacephalus", "Eryopidae", "Euskelia", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Koolasuchus: { name: "Koolasuchus", cladeList: ["Koolasuchus cleelandi", "Chigutisauridae", "Stereospondyli", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Prionosuchus: { name: "Prionosuchus", cladeList: ["Prionosuchus plummeri", "Archegosauridae", "Stereospondyli", "Temnospondyli", "Tetrapoda", "Sarcopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 11: PREHISTORIC FISH & SHARKS
  // =================================================================
  Dunkleosteus: { name: "Dunkleosteus", cladeList: ["Dunkleosteus terrelli", "Dunkleosteidae", "Arthrodira", "Placodermi", "Gnathostomata", "Vertebrata", "Craniata", "Chordata", "Deuterostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Helicoprion: { name: "Helicoprion", cladeList: ["Helicoprion bessonowi", "Helicoprionidae", "Eugeneodontida", "Holocephali", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Leedsichthys: { name: "Leedsichthys", cladeList: ["Leedsichthys problematicus", "Pachycormidae", "Pachycormiformes", "Actinopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Xiphactinus: { name: "Xiphactinus", cladeList: ["Xiphactinus audax", "Ichthyodectidae", "Ichthyodectiformes", "Actinopterygii", "Osteichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Stethacanthus: { name: "Stethacanthus", cladeList: ["Stethacanthus altonensis", "Stethacanthidae", "Symmoriida", "Holocephali", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Cretoxyrhina: { name: "Cretoxyrhina", cladeList: ["Cretoxyrhina mantelli", "Cretoxyrhinidae", "Lamniformes", "Galeomorphii", "Selachimorpha", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },
  Orthacanthus: { name: "Orthacanthus", cladeList: ["Orthacanthus senckenbergianus", "Orthacanthidae", "Xenacanthida", "Elasmobranchii", "Chondrichthyes", "Gnathostomata", "Vertebrata", "Chordata", "Metazoa"] },

  // =================================================================
  // GROUP 12: INVERTEBRATES
  // =================================================================
  Trilobite: { name: "Trilobite (Paradoxides)", cladeList: ["Paradoxides davidis", "Paradoxididae", "Redlichiida", "Trilobita", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Anomalocaris: { name: "Anomalocaris", cladeList: ["Anomalocaris canadensis", "Anomalocarididae", "Radiodonta", "Dinocaridida", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Arthropleura: { name: "Arthropleura", cladeList: ["Arthropleura armata", "Arthropleuridae", "Arthropleuridea", "Diplopoda", "Myriapoda", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Meganeura: { name: "Meganeura", cladeList: ["Meganeura monyi", "Meganeuridae", "Meganisoptera", "Odonatoptera", "Palaeoptera", "Insecta", "Hexapoda", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Metazoa"] },
  Ammonite: { name: "Ammonite", cladeList: ["Ammonoidea", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  SeaScorpion: { name: "Sea Scorpion", cladeList: ["Jaekelopterus rhenaniae", "Pterygotidae", "Eurypterida", "Chelicerata", "Arthropoda", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Hallucigenia: { name: "Hallucigenia", cladeList: ["Hallucigenia sparsa", "Hallucigeniidae", "Xenusia", "Lobopodia", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Opabinia: { name: "Opabinia", cladeList: ["Opabinia regalis", "Opabiniidae", "Dinocaridida", "Panarthropoda", "Ecdysozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Cameroceras: { name: "Cameroceras", cladeList: ["Cameroceras hennepini", "Endoceratidae", "Endocerida", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] },
  Belemnite: { name: "Belemnite", cladeList: ["Belemnoidea", "Coleoidea", "Cephalopoda", "Mollusca", "Lophotrochozoa", "Protostomia", "Bilateria", "Eumetazoa", "Metazoa"] }
};